name: End-to-end & API Tests (Cypress)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6

      - name: Guardar Screenshots de Falhas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Guardar Vídeos de Falhas
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
